server:
  port: 9001
spring:
  application:
    name: blog
    version: 1.0

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
      username: root
      password: 123456aa
      driverClassName: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20


  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  #指定mapper路径
  mapperLocations: classpath*:com/jnu/example/**/mapper/**/*.xml
  global-config:
    db-config:
      #主键类型  "数据库ID自增", "用户输入ID","全局唯一ID (数字类型唯一ID)", "全局唯一ID UUID";
      id-type: auto
      #字段策略 0:"忽略判断",1:"非NULL判断",2:"非空判断"
      field-strategy: 1
      #驼峰下划线转换
      db-column-underline: false
      #逻辑删除配置（下面3个配置）
      logic-delete-field: flag  # 全局逻辑删除字段值 3.3.0开始支持
      logic-delete-value: 1     # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    default-enum-type-handler: com.jnu.example.blog.handler.MybatisEnumTypeHandler


upload:
  rootPath: ./uploads

#日志配置
logging:
  config: classpath:log4j2.xml
